version: "3.9"

services:
  web:
    build: .
    command: gunicorn access_control_api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
